### ISSUE TITLE
PHP Fatal error: Call to undefined function SnipsHandler::hotword_detected()

### ISSUE THREAD

**Issue by CoorFun** [snipsco/Snips-JeeDom-Plugin#15]
Let's try to keep this issue here @KiboOst

**Comment by CoorFun** [comment]
Can you check if the `hotword_detected` method is defined in your `/var/www/html/plugins/snips/core/class/snips.handler.class.php` file. This should be the last function defined in the file. Please check if there are any strange characters

**Comment by CoorFun** [comment]
And also, which php version are you using ?

**Comment by KiboOst** [comment]
yes got it.
static function hotword_detected($hermes, $payload)
    {
        SnipsUtils::logger();
        SnipsUtils::set_scenario_variable(
            'snipsMsgHotwordId',
            $payload->{'modelId'}
        );
    }

It is the github master branche anyway


Version Jeedom | 3.3.19 |  
-- | -- | --
Version PHP | 5.6.33-0+deb8u1 |  
Version OS | Linux jeedom 3.14.79-94 #1 SMP PREEMPT Mon Nov 21 17:13:27 BRST 2016 aarch64 GNU/Linux  [8.7] |  
Version database | 5.5.54-0+deb8u1

**Comment by KiboOst** [comment]
I have updated platform, assistant, downloaded assistant, upload into jeedom plugin and redon the callbacks
So I’m all up to date stable version
Still broken anyway.

Also, my master appear in jeedom, but not my satellite.
tts function also seems buggy, will have a look
Uncaught exception 'Mosquitto\Exception' with message 'Invalid function arguments provided

For a stable version, well....

**Comment by KiboOst** [comment]
What have changed with this command ?
mosquitto_pub -p 1883 -t 'hermes/leds/toggleOff' -m '{\"siteId\" : \"studio\"}'

**Comment by KiboOst** [comment]
Also, when I try to disable the plugin, I got error 500 !!


:-(

**Comment by CoorFun** [comment]
The problem is that I don't have a way to reproduce your problem of `undefined function..`

There is a bug on `ask` command, I'v just fixed it. 

 nothing changed on the command `mosquitto_pub -p 1883 -t 'hermes/leds/toggleOff' -m '{"siteId" : "studio"}'`

**Comment by KiboOst** [comment]
So what can I do really ??

**Comment by KiboOst** [comment]
another one

[:error] [pid 9719] [client 192.168.0.10:52882] PHP Fatal error:  Call to a member function getName() on boolean in /var/www/html/plugins/snips/core/class/snips.class.php on line 258, referer: http://192.168.0.30/index.php?v=d&p=plugin

**Comment by CoorFun** [comment]
can you try to update your php to php7.0? 

In the official jeedom installation script, they have php7.0

FYI:
```bash
step_5_php() {
  echo "---------------------------------------------------------------------"
  echo "${JAUNE}Commence l'étape 5 php${NORMAL}"
  apt-get -y install php7.0 php7.0-curl php7.0-gd php7.0-imap php7.0-json php7.0-mcrypt php7.0-mysql php7.0-xml php7.0-opcache php7.0-soap php7.0-xmlrpc libapache2-mod-php7.0 php7.0-common php7.0-dev php7.0-zip php7.0-ssh2 php7.0-mbstring
  if [ $? -ne 0 ]; then
    apt_install libapache2-mod-php5 php5 php5-common php5-curl php5-dev php5-gd php5-json php5-memcached php5-mysqlnd php5-cli php5-ssh2 php5-redis php5-mbstring
    apt_install php5-ldap
  else
    apt-get -y install php7.0-ldap
  fi
  echo "${VERT}étape 5 php réussie${NORMAL}"
}
```

**Comment by KiboOst** [comment]
Are you serious ??
Is php 5 is not supported, write it somewhere !

This a production Jeedom Smart up to date. The migration of smart to stretch php7 is still in beta so no, I won't risk to break my entire production Jeedom.

**Comment by CoorFun** [comment]
I don't know, but I am using php7.0 which is install by Jeedom official script and most of the users have no such issue. I wonder it's more like a PHP environment setting issue.

**Comment by KiboOst** [comment]
So no one tested the beta plugin on official jeedom box ?
Wow ...
Sorry, but I'm really disappointed with all the updates issue with platform, and now this...
A nice solutioin that became a nightmare

**Comment by CoorFun** [comment]
I would purpose you the following solution, then we will see if there are something wrong:

1/ Uncomment the following in the `snips.class.php` file 
Line 10, 11 

```
ini_set("display_errors","On");
error_reporting(E_ALL);
```

2/ Add requirement in `snips.hermes.class.php` file, like following:
Line 17, 18 and 19
```
require_once dirname(__FILE__) . '/../../../../core/php/core.inc.php';
require_once dirname(__FILE__) . '/snips.utils.class.php';
require_once dirname(__FILE__) . '/snips.handler.class.php';
```
3/ Remove/ comment the following line in the `snips.class.php` file:
Line 6
```
require_once dirname(__FILE__) . '/snips.handler.class.php';
```

4/ Refresh page, re-click on install dependency, relaunch daemon.

Now if there are anymore problem will be reported in a more detailed way

**Comment by KiboOst** [comment]
I have switched my smart to stretch php7. And all is working now !
So you should really put a big requirement to not install it on smart jessis !!! 

Anyway there is another bug; when a callback scenario is executed, the scenario works, but snips always say "1" at the end. What's that ???

Not tried yet tts functions, will let you know.

But really, advert to NOT install on smart jessie !!

**Comment by CoorFun** [comment]
Update to php7 is a good step since the php5 is not updated anymore since the end of 2018. I will indicate this in the readme then. 

About scenario, it seems tts always speak the scenario execution returns. It's supposed to only play the text reply. I will check tonight.

**Comment by KiboOst** [comment]
When starting a tts command from php, it works, still say "1" at then end !! and error msg:
PHP Fatal error: Uncaught Mosquitto\Exception: Invalid function arguments provided. in /var/www/html/plugins/snips/core/class/snips.hermes.class.php:74 Stack trace: #0 /var/www/html/plugins/snips/core/class/snips.hermes.class.php(74): Mosquitto\Client->disconnect() #1 [internal function]: SnipsHermes->__destruct() #2 {main} thrown in /var/www/html/plugins/snips/core/class/snips.hermes.class.php on line 74

**Comment by KiboOst** [comment]
Of course php7 is better, like snips actions skills that should be python 3 !
But you can ask 10 000 smart user to upgrade to stretch/php7 ... migration is still in beta.

**Comment by KiboOst** [comment]
regarding TTS error here is what I do:
Just calling a commande the standard jeedom way:
$cmdTTSName = '#[Snips-Intents][Snips-TTS-salle][say]#';
$cmd = cmd::byString($cmdTTSName);
$cmd->execCmd($options=array('title'=>'', 'message'=>$message), $cache=0);

This has always worked, pure standard way to do it. Now return an error

**Comment by KiboOst** [comment]
I use tts a lot for many informations in the house, let me know if you find a fix for this.
Generating an error at each tts message isn't stable ;-)

**Comment by KiboOst** [comment]
Another bug:
I have snipsMsgHotwordId  checked, but it does nothing. No such variable set, so my scenario firing on variable change never fire ...

**Comment by KiboOst** [comment]
Hi, do you have any news ?
- Sending TTS command via code
- snipsMsgHotwordId option broken

Let me know if I can test or provide anything more. These two bugs are really a pain daily here.
Thanks

**Comment by CoorFun** [comment]
Hello,

This is fixed in the version `0.1.3`. It's available in the jeedom market now.

Thanks.

**Comment by makkil** [comment]
I confirm that this corrects the problem

jeedom 3.3.19
raspbian jessie
php 5.6.40-0+deb8u2

**Comment by KiboOst** [comment]
Just updated, the snipsMsgHotwordId  option still does NOT work ...
No variable set

Jeedom Smart stratch 3.3.19
Plugin Snips stable up to date
Snips platform up to date

**Comment by CoorFun** [comment]
@KiboOst 

This wasn't in the fixing list. Will take a look.

Next time let's try to create issue new issue instead of posting several problems under one issue. It's easier to manage when haing a lot of work to do.

**Comment by KiboOst** [comment]
Sorry, I though you fixed it.
